name: CI setup for Go
on: #on event keyword
  push:
    branches: [main] #identifying branch
    
jobs: # Job to execute on event
  my-job: # identifier for the job, just a name
    name: My Job
    runs-on: ubuntu-latest # specify OS in virtual machine
    steps:
    - name: Print a greeting
      run: |
        ls
        echo Hello there! # run terminal command
